/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.59
 * Generated at: 2026-09-14 16:58:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import entity.Product;
import entity.Category;

public final class product_list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("entity.Product");
    _jspx_imports_classes.add("entity.Category");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 List<Product> products = (List<Product>) request.getAttribute("products"); 
      out.write('\r');
      out.write('\n');
 java.util.List categories = (java.util.List) request.getAttribute("categories"); 
      out.write('\r');
      out.write('\n');
 String keyword = request.getAttribute("keyword") == null ? "" : (String) request.getAttribute("keyword"); 
      out.write('\r');
      out.write('\n');
 Long selectedCategory = request.getAttribute("selectedCategory") == null ? 0L : (Long) request.getAttribute("selectedCategory"); 
      out.write('\r');
      out.write('\n');
 int currentPage = request.getAttribute("page") == null ? 0 : ((Number) request.getAttribute("page")).intValue(); 
      out.write('\r');
      out.write('\n');
 int totalPages = request.getAttribute("totalPages") == null ? 1 : ((Number) request.getAttribute("totalPages")).intValue(); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head><meta charset=\"UTF-8\"><title>Danh sach san pham</title></head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>Danh sach san pham</h1>\r\n");
      out.write("<p><a href=\"");
      out.print( request.getContextPath() );
      out.write("/products?action=new\">Them san pham</a></p>\r\n");
      out.write("<form method=\"get\" action=\"");
      out.print( request.getContextPath() );
      out.write("/products\">\r\n");
      out.write("    Tu khoa: <input type=\"text\" name=\"keyword\" value=\"");
      out.print( keyword );
      out.write("\">\r\n");
      out.write("    Danh muc:\r\n");
      out.write("    <select name=\"categoryId\">\r\n");
      out.write("        <option value=\"\">-- Tat ca --</option>\r\n");
      out.write("        ");
 if (categories != null) { for (Object o : categories) { Category c = (Category) o; 
      out.write("\r\n");
      out.write("            <option value=\"");
      out.print( c.getId() );
      out.write('"');
      out.write(' ');
      out.print( c.getId() != null && c.getId().equals(selectedCategory) ? "selected" : "" );
      out.write('>');
      out.print( c.getName() );
      out.write("</option>\r\n");
      out.write("        ");
 } } 
      out.write("\r\n");
      out.write("    </select>\r\n");
      out.write("    <button type=\"submit\">Loc</button>\r\n");
      out.write("</form>\r\n");
      out.write("<table border=\"1\" cellpadding=\"8\">\r\n");
      out.write("    <tr><th>ID</th><th>Ten</th><th>Gia</th><th>So luong</th><th>Danh muc</th><th>Trang thai</th><th>Thao tac</th></tr>\r\n");
      out.write("    ");
 if (products != null) { for (Product product : products) { 
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td>");
      out.print( product.getId() );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( product.getName() );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( product.getPrice() );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( product.getQuatity() );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( product.getCategoryName() == null ? "-" : product.getCategoryName() );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( product.isStatus() ? "Dang ban" : "Khong ban" );
      out.write("</td>\r\n");
      out.write("        <td>\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/products?action=edit&id=");
      out.print( product.getId() );
      out.write("\">Sua</a>\r\n");
      out.write("            <form method=\"post\" action=\"");
      out.print( request.getContextPath() );
      out.write("/products\" style=\"display:inline\">\r\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"delete\" />\r\n");
      out.write("                <input type=\"hidden\" name=\"id\" value=\"");
      out.print( product.getId() );
      out.write("\" />\r\n");
      out.write("                <button type=\"submit\" onclick=\"return confirm('Xóa sản phẩm này?')\">Xóa</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");
 } } 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<div>\r\n");
      out.write("    ");
 if (totalPages > 1) { 
      out.write("\r\n");
      out.write("        ");
 int prevPage = Math.max(0, currentPage - 1); 
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/products?keyword=");
      out.print( java.net.URLEncoder.encode(keyword, "UTF-8") );
      out.write("&categoryId=");
      out.print( selectedCategory );
      out.write("&page=");
      out.print( prevPage );
      out.write("\">Prev</a>\r\n");
      out.write("        ");
 for (int i = 1; i <= totalPages; i++) {
               int pageParam = i - 1;
               if (pageParam == currentPage) { 
      out.write("\r\n");
      out.write("                   <strong>");
      out.print( i );
      out.write("</strong>\r\n");
      out.write("               ");
 } else { 
      out.write("\r\n");
      out.write("                   <a href=\"");
      out.print( request.getContextPath() );
      out.write("/products?keyword=");
      out.print( java.net.URLEncoder.encode(keyword, "UTF-8") );
      out.write("&categoryId=");
      out.print( selectedCategory );
      out.write("&page=");
      out.print( pageParam );
      out.write('"');
      out.write('>');
      out.print( i );
      out.write("</a>\r\n");
      out.write("               ");
 }
           } 
      out.write("\r\n");
      out.write("        ");
 int nextPage = Math.min(totalPages - 1, currentPage + 1); 
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/products?keyword=");
      out.print( java.net.URLEncoder.encode(keyword, "UTF-8") );
      out.write("&categoryId=");
      out.print( selectedCategory );
      out.write("&page=");
      out.print( nextPage );
      out.write("\">Next</a>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
